include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v1/.cscs.yml'

stages:
  - build
  - test
  - notify

##
## BUILDS
##

.build_common:
  extends: .dind
  stage: build
  only:
    - master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - docker login -u $CSCS_REGISTRY_USER -p $CSCS_REGISTRY_PASSWORD $CSCS_REGISTRY
  script:
    - TAG=`sha256sum $BUILD_DOCKER_FILE | head -c 64`
    - docker build -t $BUILD_IMAGE:$TAG -t $BUILD_IMAGE:latest --cache-from $BUILD_IMAGE:$TAG --cache-from $BUILD_IMAGE:latest --build-arg BASE_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg HPX_WITH_CUDA -f $BUILD_DOCKER_FILE --network=host .
    - docker push $BUILD_IMAGE:$TAG
    - docker push $BUILD_IMAGE:latest

# Builds a Docker image for the current commit
cpu release build:
  extends: .build_common
  variables:
    BUILD_DOCKER_FILE: ci/docker/release/build.Dockerfile
    BUILD_IMAGE: $CSCS_REGISTRY_IMAGE/release-cpu/build
    DLAI_WITH_CUDA: 'OFF'
    BASE_IMAGE: ubuntu:20.04
    HPX_WITH_CUDA: "OFF"

cpu codecov build:
  extends: .build_common
  variables:
    BUILD_DOCKER_FILE: ci/docker/codecov/build.Dockerfile
    BUILD_IMAGE: $CSCS_REGISTRY_IMAGE/codecov-cpu/build
    DLAI_WITH_CUDA: 'OFF'
    BASE_IMAGE: ubuntu:20.04
    HPX_WITH_CUDA: "OFF"

