# HPX_LINALG_DIR contains the path to HPX_LINALGConfig.cmake
# DLA_HAVE_HPX_LINALG is set to ON if HPX_LINALG is available, OFF otherwise.
# DLA_HPX_LINALG_INCLUDE_DIRS provides the generated include paths for hpx_linalg.
# DLA_HPX_LINALG_LIBRARIES provides the generated link line for hpx_linalg.

function(dla_find_hpx_linalg)
	set(DLA_HAVE_HPX_LINALG_INTERNAL OFF)
	unset(HPX_LINALG_FOUND CACHE)

	if (HPX_LINALGROOT)
		setoption(HPX_LINALG_DIR PATH ${HPX_LINALG}/lib/cmake "HPX_LINALG_DIR directory")
	else()
		message(STATUS "To enable HPX_LINALG must set HPX_LINALGROOT variable!")
	endif()
	
	if(HPX_LINALG_DIR)
		find_package(HPX_LINALG CONFIG)

		if (HPX_LINALG_FOUND)
			link_directories(${HPX_LINALG_LINK_DIRECTORIES})
			set(DLA_HPX_LINALG_INCLUDE_DIRS ${HPX_LINALG_INCLUDE_DIRECTORIES} CACHE STRING "Include paths for HPX_LINALG")
			set(DLA_HPX_LINALG_LIBRARIES HPX_LINALG::hpx_linalg CACHE STRING "Libraries for HPX_LINALG")
			set(CMAKE_REQUIRED_INCLUDES ${DLA_HPX_LINALG_INCLUDE_DIRS})
			set(CMAKE_REQUIRED_LIBRARIES ${DLA_HPX_LINALG_LIBRARIES})
			set(DLA_HAVE_HPX_LINALG_INTERNAL ON)
			set(DLA_HAVE_HPX_LINALG ${DLA_HAVE_HPX_LINALG_INTERNAL} CACHE BOOL "HPX_LINALG is available (autogenerated)" FORCE)
			message(STATUS "Found HPX LINALG.")
		else()
			message(STATUS "HPX_LINALG not found.")
		endif()

		if (DLA_HAVE_HPX_LINALG)
			add_definitions(-DDLA_HAVE_HPX_LINALG)
		endif()
	endif()

endfunction()
