# PARSEC_DIR contains the path to ParsecConfig.cmake
# PLASMA_DIR contains the directory in which plasma is installed.
# (${PLASMA_DIR}\lib\pkgconfig contains coreblas.pc}
# DLA_HAVE_DPLASMA is set to ON if dplasma is available, OFF otherwise.
# DLA_DPLASMA_INCLUDE provides the generated include paths for dplasma.
# DLA_DPLASMA_LIBRARY provides the generated link line for dplasma.

include(CheckCXXSymbolExists)

function(dla_find_dplasma)
  set(DLA_HAVE_DPLASMA_INTERNAL OFF)
  unset(COREBLAS_FOUND CACHE)
  unset(Parsec_FOUND CACHE)
  unset(DPLASMA_FOUND CACHE)
  
  if (NOT Parsec_DIR AND PARSEC_DIR)
    set(Parsec_DIR ${PARSEC_DIR})
  endif()

  if (Parsec_DIR)
    find_package(Parsec NO_MODULE)
    if (Parsec_FOUND)

      if(NOT PLASMA_DIR)
        message(FATAL_ERROR "PLASMA_DIR not specified")
      endif()

      set(CMAKE_PREFIX_PATH ${PLASMA_DIR})
      find_package(PkgConfig REQUIRED)
      pkg_search_module(COREBLAS REQUIRED coreblas)
      unset(CMAKE_PREFIX_PATH)

      if(NOT COREBLAS_FOUND)
        message(FATAL_ERROR "${COREBLAS_PKG_DIR}/coreblas.pc does not exist")
      endif()

      set(DLA_DPLASMA_LIB_DIR "-Wl,-rpath,${PARSEC_DIR}/dplasma/lib;-L${PARSEC_DIR}/dplasma/lib;-Wl,-rpath,${PARSEC_DIR}/lib;-L${PARSEC_DIR}/lib;-L${COREBLAS_LIBDIR}")

      set(DLA_DPLASMA_INCLUDE_DIRS ${PARSEC_INCLUDE_DIRS} ${PARSEC_DIR}/dplasma/include ${PARSEC_DIR}/include/parsec ${COREBLAS_INCLUDE_DIRS} CACHE STRING "Include paths for DPlasma") 
      set(DLA_DPLASMA_LIBS "${DLA_DPLASMA_LIB_DIR};dplasma;parsec_distribution_matrix;parsec;${PARSEC_LIBRARIES};coreblas" CACHE STRING "Libraries for DPlasma")

      set(CMAKE_REQUIRED_INCLUDES "${PROJECT_SOURCE_DIR}/include" "${MPI_CXX_INCLUDE_PATH}" "${DLA_DPLASMA_INCLUDE_DIRS}")
      set(CMAKE_REQUIRED_LIBRARIES "${CMAKE_EXE_LINKER_FLAGS}" "${MPI_CXX_LIBRARIES}" "${DLA_DPLASMA_LIBS}")

      CHECK_CXX_SYMBOL_EXISTS(dplasma_map ordered_dplasma.h DPLASMA_FOUND)
      if (DPLASMA_FOUND)
        set(DLA_HAVE_DPLASMA_INTERNAL ON)
      else()
        unset(DLA_DPLASMA_INCLUDE_DIRS)
        unset(DLA_DPLASMA_LIBS)
        message(FATAL_ERROR "ParSEC is configured without DPLASMA!")
      endif()
    endif()
    set(DLA_HAVE_DPLASMA ${DLA_HAVE_DPLASMA_INTERNAL} CACHE BOOL "Dplasma is available (autogenerated)" FORCE)
  endif()

  if (DLA_HAVE_DPLASMA)
    add_definitions(-DDLA_HAVE_DPLASMA)
  endif()

endfunction()
